INSERT INTO [dbo].[Menu] ([MenuID], [Drinks_Name], [Category], [Price], [ImageUrl]) VALUES (N'C001', N'Cafe Latte', N'Coffee    ', CAST(15.0000 AS Money), N'Assets/latte2.PNG')
INSERT INTO [dbo].[Menu] ([MenuID], [Drinks_Name], [Category], [Price], [ImageUrl]) VALUES (N'C002', N'Espresso  ', N'Coffee    ', CAST(10.0000 AS Money), N'Assets/espresso.PNG')
INSERT INTO [dbo].[Menu] ([MenuID], [Drinks_Name], [Category], [Price], [ImageUrl]) VALUES (N'C003', N'Americano ', N'Coffee    ', CAST(12.0000 AS Money), N'Assets/americano.PNG')
INSERT INTO [dbo].[Menu] ([MenuID], [Drinks_Name], [Category], [Price], [ImageUrl]) VALUES (N'C004', N'Matcha Coffee', N'Coffee    ', CAST(18.0000 AS Money), N'Assets/matchacoffee.PNG')
INSERT INTO [dbo].[Menu] ([MenuID], [Drinks_Name], [Category], [Price], [ImageUrl]) VALUES (N'C005', N'Mocha', N'Coffee    ', CAST(18.0000 AS Money), N'Assets/mocha.PNG')
INSERT INTO [dbo].[Menu] ([MenuID], [Drinks_Name], [Category], [Price], [ImageUrl]) VALUES (N'F001', N'Choco Frappe', N'Frappe    ', CAST(20.0000 AS Money), N'Assets/chocofrappe.PNG')
INSERT INTO [dbo].[Menu] ([MenuID], [Drinks_Name], [Category], [Price], [ImageUrl]) VALUES (N'F002', N'Strawberry Frappe', N'Frappe    ', CAST(20.0000 AS Money), N'Assets/strawberryfrappe.PNG')
INSERT INTO [dbo].[Menu] ([MenuID], [Drinks_Name], [Category], [Price], [ImageUrl]) VALUES (N'F003', N'Caramel Espresso Frappe', N'Frappe    ', CAST(20.0000 AS Money), N'Assets/caramelespressofrappe.PNG')
INSERT INTO [dbo].[Menu] ([MenuID], [Drinks_Name], [Category], [Price], [ImageUrl]) VALUES (N'F004', N'Mocha Frappe', N'Frappe    ', CAST(20.0000 AS Money), N'Assets/mochafrappe.PNG')
INSERT INTO [dbo].[Menu] ([MenuID], [Drinks_Name], [Category], [Price], [ImageUrl]) VALUES (N'F005', N'Matcha Frappe', N'Frappe    ', CAST(20.0000 AS Money), N'Assets/matchafrappe.PNG')
INSERT INTO [dbo].[Menu] ([MenuID], [Drinks_Name], [Category], [Price], [ImageUrl]) VALUES (N'N001', N'Chocolate latte', N'NonCoffee ', CAST(16.0000 AS Money), N'Assets/chocolatte.PNG')
INSERT INTO [dbo].[Menu] ([MenuID], [Drinks_Name], [Category], [Price], [ImageUrl]) VALUES (N'N002', N'Matcha Latte', N'NonCoffee ', CAST(16.0000 AS Money), N'Assets/matchalatte.PNG')
INSERT INTO [dbo].[Menu] ([MenuID], [Drinks_Name], [Category], [Price], [ImageUrl]) VALUES (N'N003', N'Brown Sugar Latte', N'NonCoffee ', CAST(15.0000 AS Money), N'Assets/brownsugarlatte.PNG')
INSERT INTO [dbo].[Menu] ([MenuID], [Drinks_Name], [Category], [Price], [ImageUrl]) VALUES (N'O001', N'Hot', N'Custom    ', CAST(0.0000 AS Money), NULL)
INSERT INTO [dbo].[Menu] ([MenuID], [Drinks_Name], [Category], [Price], [ImageUrl]) VALUES (N'O002', N'Ice (R)', N'Custom    ', CAST(0.0000 AS Money), NULL)
INSERT INTO [dbo].[Menu] ([MenuID], [Drinks_Name], [Category], [Price], [ImageUrl]) VALUES (N'O003', N'Ice (L) (+RM 2)', N'Custom    ', CAST(2.0000 AS Money), NULL)
INSERT INTO [dbo].[Menu] ([MenuID], [Drinks_Name], [Category], [Price], [ImageUrl]) VALUES (N'OD001', N'Chocolate Drizzle (+RM 3)', N'Custom    ', CAST(3.0000 AS Money), NULL)
INSERT INTO [dbo].[Menu] ([MenuID], [Drinks_Name], [Category], [Price], [ImageUrl]) VALUES (N'OD002', N'Caramel Drizzle (+RM 3)', N'Custom    ', CAST(3.0000 AS Money), NULL)
INSERT INTO [dbo].[Menu] ([MenuID], [Drinks_Name], [Category], [Price], [ImageUrl]) VALUES (N'OD003', N'Strawberry Drizzle (+RM 3)', N'Custom    ', CAST(3.0000 AS Money), NULL)
INSERT INTO [dbo].[Menu] ([MenuID], [Drinks_Name], [Category], [Price], [ImageUrl]) VALUES (N'OS001', N'Normal Syrup', N'Custom    ', CAST(0.0000 AS Money), NULL)
INSERT INTO [dbo].[Menu] ([MenuID], [Drinks_Name], [Category], [Price], [ImageUrl]) VALUES (N'OS002', N'Hazelnut Syrup (+RM2))', N'Custom    ', CAST(2.0000 AS Money), NULL)
INSERT INTO [dbo].[Menu] ([MenuID], [Drinks_Name], [Category], [Price], [ImageUrl]) VALUES (N'OS003', N'Caramel Syrup (+RM 2)', N'Custom    ', CAST(2.0000 AS Money), NULL)
INSERT INTO [dbo].[Menu] ([MenuID], [Drinks_Name], [Category], [Price], [ImageUrl]) VALUES (N'OS004', N'Rose Syrup (+RM 2)', N'Custom    ', CAST(2.0000 AS Money), NULL)
INSERT INTO [dbo].[Menu] ([MenuID], [Drinks_Name], [Category], [Price], [ImageUrl]) VALUES (N'OS005', N'Vanilla Syrup(+RM 2)', N'Custom    ', CAST(2.0000 AS Money), NULL)
INSERT INTO [dbo].[Menu] ([MenuID], [Drinks_Name], [Category], [Price], [ImageUrl]) VALUES (N'T001', N'Green Tea', N'Tea       ', CAST(10.0000 AS Money), N'Assets/greentea.PNG')
INSERT INTO [dbo].[Menu] ([MenuID], [Drinks_Name], [Category], [Price], [ImageUrl]) VALUES (N'T002', N'Black Tea', N'Tea       ', CAST(10.0000 AS Money), N'Assets/blacktea.PNG')
INSERT INTO [dbo].[Menu] ([MenuID], [Drinks_Name], [Category], [Price], [ImageUrl]) VALUES (N'T003', N'Oolong Tea', N'Tea       ', CAST(10.0000 AS Money), N'Assets/oolongtea.PNG')
